#pragma once

#include <string>

namespace sv {
namespace Keycodes {
enum Enum {
    KEY_FIRST = 0x0,

    KEY_BACKSPACE    = '\b',
    KEY_TAB          = '\t',
    KEY_RETURN       = '\r',
    KEY_ESCAPE       = '\033',
    KEY_SPACEBAR     = ' ',
    KEY_EXCLAMATION  = '!',
    KEY_DBLQUOTE     = '\"',
    KEY_HASH         = '#',
    KEY_DOLLAR       = '$',
    KEY_PERCENT      = '%',
    KEY_AMPERSAND    = '&',
    KEY_QUOTE        = '\'',
    KEY_LEFTPAREN    = '(',
    KEY_RIGHTPAREN   = ')',
    KEY_ASTERISK     = '*',
    KEY_PLUS         = '+',
    KEY_COMMA        = ',',
    KEY_MINUS        = '-',
    KEY_PERIOD       = '.',
    KEY_SLASH        = '/',
    KEY_0            = '0',
    KEY_1            = '1',
    KEY_2            = '2',
    KEY_3            = '3',
    KEY_4            = '4',
    KEY_5            = '5',
    KEY_6            = '6',
    KEY_7            = '7',
    KEY_8            = '8',
    KEY_9            = '9',
    KEY_COLON        = ':',
    KEY_SEMICOLON    = ';',
    KEY_LESS         = '<',
    KEY_GREATER      = '>',
    KEY_QUESTION     = '?',
    KEY_AT           = '@',
    KEY_LEFTBRACKET  = '[',
    KEY_RIGHTBRACKET = ']',
    KEY_CARET        = '^',
    KEY_UNDERSCORE   = '_',
    KEY_BACKQUOTE    = '`',
    KEY_A            = 'a',
    KEY_B            = 'b',
    KEY_C            = 'c',
    KEY_D            = 'd',
    KEY_E            = 'e',
    KEY_F            = 'f',
    KEY_G            = 'g',
    KEY_H            = 'h',
    KEY_I            = 'i',
    KEY_J            = 'j',
    KEY_K            = 'k',
    KEY_L            = 'l',
    KEY_M            = 'm',
    KEY_N            = 'n',
    KEY_O            = 'o',
    KEY_P            = 'p',
    KEY_Q            = 'q',
    KEY_R            = 'r',
    KEY_S            = 's',
    KEY_T            = 't',
    KEY_U            = 'u',
    KEY_V            = 'v',
    KEY_W            = 'w',
    KEY_X            = 'x',
    KEY_Y            = 'y',
    KEY_Z            = 'z',
    KEY_DELETE       = '\177',
    KEY_CAPSLOCK     = 0x40000039,
    KEY_F1           = 0x4000003A,
    KEY_F2           = 0x4000003B,
    KEY_F3           = 0x4000003C,
    KEY_F4           = 0x4000003D,
    KEY_F5           = 0x4000003E,
    KEY_F6           = 0x4000003F,
    KEY_F7           = 0x40000040,
    KEY_F8           = 0x40000041,
    KEY_F9           = 0x40000042,
    KEY_F10          = 0x40000043,
    KEY_F11          = 0x40000044,
    KEY_F12          = 0x40000045,
    KEY_PRINTSCREEN  = 0x40000046,
    KEY_SCROLLLOCK   = 0x40000047,
    KEY_PAUSE        = 0x40000048,
    KEY_INSERT       = 0x40000049,
    KEY_HOME         = 0x4000004A,
    KEY_PAGEUP       = 0x4000004B,
    KEY_END          = 0x4000004D,
    KEY_PAGEDOWN     = 0x4000004E,
    KEY_RIGHTARROW   = 0x4000004F,
    KEY_LEFTARROW    = 0x40000050,
    KEY_DOWNARROW    = 0x40000051,
    KEY_UPARROW      = 0x40000052,
    KEY_LEFTCTRL     = 0x400000E0,
    KEY_LEFTSHIFT    = 0x400000E1,
    KEY_LEFTALT      = 0x400000E2,
    KEY_LEFTGUI      = 0x400000E3, // Windows key, command key, meta
    KEY_RIGHTCTRL    = 0x400000E4,
    KEY_RIGHTSHIFT   = 0x400000E5,
    KEY_RIGHTALT     = 0x400000E6,

    KEY_MOUSE1,
    KEY_MOUSE2,
    KEY_MOUSE3,
    KEY_MOUSE4,
    KEY_MOUSE5,

    KEY_MWHEELDOWN,
    KEY_MWHEELUP,

    KEY_LAST = ~0x0,
};
}

std::string getKeycodeString(Keycodes::Enum keycode);
}
